name: Transform Tokens

on:
  push:
    branches:
      - main
    paths:
      - src/assets/tokens/tokens.json

jobs:
  transform-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Run Token Transformer
        run: |
            node ./src/assets/tokens/transformToken.js
            git config --global user.name "doraeza"
            git config --global user.email "pp8960@naver.com"
            git add .
            git commit -m 'Figma updated styles'
            git push
        env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Run transform script
        run: node ./src/assets/tokens/transformToken.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Transform tokens and update styles
          branch: transform-tokens-branch
          title: "Transform tokens and update styles"
          body: "This PR transforms tokens and updates styles automatically."
          base: main
